### ISSUE TITLE
Installing app broke NextCloud installation

### ISSUE THREAD

**Issue by StarSmasher44** [eneiluj/integration_onedrive#10]
So I went ahead and installed this app, the site worked for a small period after but then died on a 500 Error. I can't even use occ commands any more because of the following error:
And I had not even started configuration of the app, I only installed it.

![image](https://user-images.githubusercontent.com/1653200/103231566-62d42a80-4938-11eb-98fa-1be0ab8c058f.png)

I am unsure how to fix the problem nor the installation, I can revert the entire OS but I hope that will not be needed.

**Comment by eneiluj** [comment]
Hi, you're in the wrong project here. From your log content, your problem is rather related to this app : https://github.com/hevelius/files_external_onedrive .

A first thing you could try is to manually delete the `/var/www/nextcloud/apps/files_external_onedrive` directory. This will most likely bring your Nextcloud back to life.

**Comment by StarSmasher44** [comment]
Hi, yeah I was about to delete this once I saw the stupidity of my mistake but you beat me to it.
I'm sorry for the disturbance, all has been resolved using your tip. I was just baffled at first but deleting the wrong folder won't do any good :P
